using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace enx_fit.Migrations;

public partial class ExerciseIdentifiersAsGuids : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        DropExerciseForeignKeys(migrationBuilder);
        // Keep every existing row, including administrator-created exercises and renames.
        // The namespace matches ExerciseIds.FromLegacy; signed integers map bijectively.
        migrationBuilder.Sql("""
            CREATE OR REPLACE FUNCTION pg_temp.enix_exercise_uuid(id integer) RETURNS uuid
            LANGUAGE sql IMMUTABLE STRICT AS $fn$
              SELECT CASE WHEN id = 0 THEN '00000000-0000-0000-0000-000000000000'::uuid
                ELSE ('e71c15e5-0000-4000-8000-0000' || lpad(to_hex(id::bigint & 4294967295), 8, '0'))::uuid END
            $fn$;

            ALTER TABLE "Exercises" ALTER COLUMN "Id" DROP IDENTITY IF EXISTS;
            ALTER TABLE "Exercises" ALTER COLUMN "Id" DROP DEFAULT;
            ALTER TABLE "Exercises" ALTER COLUMN "Id" TYPE uuid USING pg_temp.enix_exercise_uuid("Id");
            ALTER TABLE "WorkoutExercises" ALTER COLUMN "ExerciseId" TYPE uuid USING pg_temp.enix_exercise_uuid("ExerciseId");
            ALTER TABLE "ProgramWorkoutExercise" ALTER COLUMN "ExerciseId" TYPE uuid USING pg_temp.enix_exercise_uuid("ExerciseId");
            ALTER TABLE "TrainingRecommendations" ALTER COLUMN "ExerciseId" TYPE uuid USING pg_temp.enix_exercise_uuid("ExerciseId");

            CREATE OR REPLACE FUNCTION pg_temp.enix_json_exercise_id(value jsonb) RETURNS jsonb
            LANGUAGE sql IMMUTABLE STRICT AS $fn$
              SELECT CASE WHEN jsonb_typeof(value) = 'number'
                THEN to_jsonb(pg_temp.enix_exercise_uuid((value #>> '{}')::integer)) ELSE value END
            $fn$;
            """);
        ConvertStoredJson(migrationBuilder);
        AddExerciseForeignKeys(migrationBuilder);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        DropExerciseForeignKeys(migrationBuilder);
        // Newly created UUID exercises also survive rollback: allocate unused positive IDs.
        migrationBuilder.Sql("""
            CREATE TEMP TABLE enix_exercise_ids (id uuid PRIMARY KEY, legacy_id integer UNIQUE NOT NULL) ON COMMIT DROP;
            INSERT INTO enix_exercise_ids
              SELECT "Id", ('x' || right("Id"::text, 8))::bit(32)::integer
              FROM "Exercises" WHERE "Id"::text LIKE 'e71c15e5-0000-4000-8000-0000%';
            INSERT INTO enix_exercise_ids
              SELECT "Id", ((SELECT greatest(coalesce(max(legacy_id), 0), 0) FROM enix_exercise_ids)
                + row_number() OVER (ORDER BY "Id"))::integer
              FROM "Exercises" WHERE "Id" NOT IN (SELECT id FROM enix_exercise_ids);

            CREATE OR REPLACE FUNCTION pg_temp.enix_legacy_exercise_id(value uuid) RETURNS integer
            LANGUAGE sql STRICT AS $fn$
              SELECT CASE WHEN value = '00000000-0000-0000-0000-000000000000'::uuid THEN 0
                ELSE coalesce((SELECT legacy_id FROM pg_temp.enix_exercise_ids WHERE id = value),
                  CASE WHEN value::text LIKE 'e71c15e5-0000-4000-8000-0000%'
                    THEN ('x' || right(value::text, 8))::bit(32)::integer END) END
            $fn$;
            CREATE OR REPLACE FUNCTION pg_temp.enix_json_exercise_id(value jsonb) RETURNS jsonb
            LANGUAGE sql STRICT AS $fn$
              SELECT CASE WHEN jsonb_typeof(value) = 'string'
                THEN coalesce(to_jsonb(pg_temp.enix_legacy_exercise_id((value #>> '{}')::uuid)), value) ELSE value END
            $fn$;
            """);
        ConvertStoredJson(migrationBuilder);
        migrationBuilder.Sql("""
            ALTER TABLE "WorkoutExercises" ALTER COLUMN "ExerciseId" TYPE integer USING pg_temp.enix_legacy_exercise_id("ExerciseId");
            ALTER TABLE "ProgramWorkoutExercise" ALTER COLUMN "ExerciseId" TYPE integer USING pg_temp.enix_legacy_exercise_id("ExerciseId");
            ALTER TABLE "TrainingRecommendations" ALTER COLUMN "ExerciseId" TYPE integer USING pg_temp.enix_legacy_exercise_id("ExerciseId");
            ALTER TABLE "Exercises" ALTER COLUMN "Id" TYPE integer USING pg_temp.enix_legacy_exercise_id("Id");
            ALTER TABLE "Exercises" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
            SELECT setval(pg_get_serial_sequence('"Exercises"', 'Id'), greatest(coalesce(max("Id"), 0), 1), true) FROM "Exercises";
            """);
        AddExerciseForeignKeys(migrationBuilder);
    }

    private static void ConvertStoredJson(MigrationBuilder migrationBuilder) => migrationBuilder.Sql("""
        CREATE OR REPLACE FUNCTION pg_temp.enix_exercise_json(value jsonb) RETURNS jsonb
        LANGUAGE plpgsql STRICT AS $fn$
        BEGIN
          IF jsonb_typeof(value) = 'object' THEN
            RETURN (SELECT coalesce(jsonb_object_agg(key, CASE WHEN lower(key) = 'exerciseid'
              THEN pg_temp.enix_json_exercise_id(item) ELSE pg_temp.enix_exercise_json(item) END), '{}'::jsonb)
              FROM jsonb_each(value) AS entry(key, item));
          ELSIF jsonb_typeof(value) = 'array' THEN
            RETURN (SELECT coalesce(jsonb_agg(pg_temp.enix_exercise_json(item) ORDER BY position), '[]'::jsonb)
              FROM jsonb_array_elements(value) WITH ORDINALITY AS entry(item, position));
          END IF;
          RETURN value;
        END
        $fn$;
        UPDATE "WorkoutSessions" SET "BuilderConfigurationJson" = pg_temp.enix_exercise_json("BuilderConfigurationJson"::jsonb)::text
          WHERE "BuilderConfigurationJson" IS NOT NULL;
        UPDATE "WorkoutSessions" SET "SourceStructureJson" = pg_temp.enix_exercise_json("SourceStructureJson"::jsonb)::text
          WHERE "SourceStructureJson" IS NOT NULL;
        """);

    private static void DropExerciseForeignKeys(MigrationBuilder migrationBuilder)
    {
        foreach (var table in new[] { "WorkoutExercises", "ProgramWorkoutExercise", "TrainingRecommendations" })
            migrationBuilder.DropForeignKey($"FK_{table}_Exercises_ExerciseId", table);
    }

    private static void AddExerciseForeignKeys(MigrationBuilder migrationBuilder)
    {
        foreach (var table in new[] { "WorkoutExercises", "ProgramWorkoutExercise", "TrainingRecommendations" })
            migrationBuilder.AddForeignKey($"FK_{table}_Exercises_ExerciseId", table, "ExerciseId", "Exercises",
                principalColumn: "Id", onDelete: ReferentialAction.Restrict);
    }
}
